/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itse322;

/**
 *
 * @author Zenjar
 */
public class AdminUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminUI
     */
    public AdminUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerTabbedPane = new javax.swing.JTabbedPane();
        coachManagementPanel = new javax.swing.JPanel();
        coachManagementSplitPane = new javax.swing.JSplitPane();
        coachListPanel = new javax.swing.JPanel();
        coachListScrollPane = new javax.swing.JScrollPane();
        coachListList = new javax.swing.JList<>();
        coachInfoPanel = new javax.swing.JPanel();
        clientManagementPanel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        coachManagementSplitPane.setDividerLocation(150);

        coachListList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "ali mohamed", "mohamed ali", "ahmed mohamed", "ahmed ali", "mohamed ahmed", "ali ahmed" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        coachListList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        coachListScrollPane.setViewportView(coachListList);

        javax.swing.GroupLayout coachListPanelLayout = new javax.swing.GroupLayout(coachListPanel);
        coachListPanel.setLayout(coachListPanelLayout);
        coachListPanelLayout.setHorizontalGroup(
            coachListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coachListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        coachListPanelLayout.setVerticalGroup(
            coachListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coachListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );

        coachManagementSplitPane.setLeftComponent(coachListPanel);

        coachInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Coach Info"));

        javax.swing.GroupLayout coachInfoPanelLayout = new javax.swing.GroupLayout(coachInfoPanel);
        coachInfoPanel.setLayout(coachInfoPanelLayout);
        coachInfoPanelLayout.setHorizontalGroup(
            coachInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        coachInfoPanelLayout.setVerticalGroup(
            coachInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        coachManagementSplitPane.setRightComponent(coachInfoPanel);

        javax.swing.GroupLayout coachManagementPanelLayout = new javax.swing.GroupLayout(coachManagementPanel);
        coachManagementPanel.setLayout(coachManagementPanelLayout);
        coachManagementPanelLayout.setHorizontalGroup(
            coachManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coachManagementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coachManagementSplitPane)
                .addContainerGap())
        );
        coachManagementPanelLayout.setVerticalGroup(
            coachManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coachManagementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coachManagementSplitPane)
                .addContainerGap())
        );

        containerTabbedPane.addTab("Coach Management", coachManagementPanel);

        jSplitPane1.setDividerLocation(150);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout clientManagementPanelLayout = new javax.swing.GroupLayout(clientManagementPanel);
        clientManagementPanel.setLayout(clientManagementPanelLayout);
        clientManagementPanelLayout.setHorizontalGroup(
            clientManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientManagementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        clientManagementPanelLayout.setVerticalGroup(
            clientManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientManagementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        containerTabbedPane.addTab("Client Management", clientManagementPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel clientManagementPanel;
    private javax.swing.JPanel coachInfoPanel;
    private javax.swing.JList<String> coachListList;
    private javax.swing.JPanel coachListPanel;
    private javax.swing.JScrollPane coachListScrollPane;
    private javax.swing.JPanel coachManagementPanel;
    private javax.swing.JSplitPane coachManagementSplitPane;
    private javax.swing.JTabbedPane containerTabbedPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
