/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itse322;

// Imports
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zenjar
 */
public class ClientUI extends javax.swing.JFrame {

    /**
     * Creates new form ClientUI
     */
    public ClientUI(Client user) {
        initComponents();
        this.user = user;
        
        // Hide Error Message Until Necessary
        errorMessage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContainer = new javax.swing.JTabbedPane();
        trainingPanel = new javax.swing.JPanel();
        weekSelectorLabel = new javax.swing.JLabel();
        weekSelector = new javax.swing.JComboBox<>();
        trainingScheduleContainer = new javax.swing.JScrollPane();
        trainingSchedule = new javax.swing.JTable();
        coachPanel = new javax.swing.JPanel();
        coachIDLabel = new javax.swing.JLabel();
        coachIDValue = new javax.swing.JLabel();
        coachFirstNameLabel = new javax.swing.JLabel();
        coachFirstNameField = new javax.swing.JTextField();
        coachLastNameLabel = new javax.swing.JLabel();
        coachLastNameField = new javax.swing.JTextField();
        coachPhoneLabel = new javax.swing.JLabel();
        coachPhoneField = new javax.swing.JTextField();
        coachEmailLabel = new javax.swing.JLabel();
        coachEmailField = new javax.swing.JTextField();
        coachFirstYearLabel = new javax.swing.JLabel();
        coachFirstYearSpinner = new javax.swing.JSpinner();
        personalPanel = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        idValueLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        birthDateLabel = new javax.swing.JLabel();
        birthDateSpinner = new javax.swing.JSpinner();
        genderLabel = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        tierLabel = new javax.swing.JLabel();
        tierComboBox = new javax.swing.JComboBox<>();
        expiryDateLabel = new javax.swing.JLabel();
        expiryDateSpinner = new javax.swing.JSpinner();
        heightLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        heightField = new javax.swing.JTextField();
        weightField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        cmLabel = new javax.swing.JLabel();
        kgLabel = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        errorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        weekSelectorLabel.setText("Choose Day of the Week:");

        weekSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday" }));
        weekSelector.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                weekSelectorItemStateChanged(evt);
            }
        });

        trainingSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exercise", "Sets", "Reps"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        trainingSchedule.setShowHorizontalLines(true);
        trainingSchedule.setShowVerticalLines(true);
        trainingSchedule.getTableHeader().setReorderingAllowed(false);
        trainingScheduleContainer.setViewportView(trainingSchedule);

        javax.swing.GroupLayout trainingPanelLayout = new javax.swing.GroupLayout(trainingPanel);
        trainingPanel.setLayout(trainingPanelLayout);
        trainingPanelLayout.setHorizontalGroup(
            trainingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(trainingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(trainingPanelLayout.createSequentialGroup()
                        .addComponent(weekSelectorLabel)
                        .addGap(18, 18, 18)
                        .addComponent(weekSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(trainingScheduleContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        trainingPanelLayout.setVerticalGroup(
            trainingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(trainingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weekSelectorLabel)
                    .addComponent(weekSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(trainingScheduleContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        panelContainer.addTab("Training Schedule", trainingPanel);

        coachIDLabel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        coachIDLabel.setText("Coach ID:");

        coachIDValue.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        coachIDValue.setText("232");

        coachFirstNameLabel.setText("First Name:");

        coachFirstNameField.setEnabled(false);

        coachLastNameLabel.setText("Last Name:");

        coachLastNameField.setEnabled(false);

        coachPhoneLabel.setText("Phone Number:");

        coachPhoneField.setEnabled(false);

        coachEmailLabel.setText("Email:");

        coachEmailField.setEnabled(false);

        coachFirstYearLabel.setText("First Year of Coaching:");

        coachFirstYearSpinner.setModel(new javax.swing.SpinnerDateModel());
        coachFirstYearSpinner.setEditor(new javax.swing.JSpinner.DateEditor(coachFirstYearSpinner, "yyyy"));
        coachFirstYearSpinner.setEnabled(false);

        javax.swing.GroupLayout coachPanelLayout = new javax.swing.GroupLayout(coachPanel);
        coachPanel.setLayout(coachPanelLayout);
        coachPanelLayout.setHorizontalGroup(
            coachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coachPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(coachPhoneField)
                    .addComponent(coachPhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(coachFirstNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, coachPanelLayout.createSequentialGroup()
                        .addComponent(coachIDLabel)
                        .addGap(18, 18, 18)
                        .addComponent(coachIDValue))
                    .addComponent(coachFirstNameField, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(coachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coachLastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(coachLastNameField)
                    .addComponent(coachEmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coachEmailField))
                .addGap(18, 18, 18)
                .addGroup(coachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coachFirstYearLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coachFirstYearSpinner))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        coachPanelLayout.setVerticalGroup(
            coachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coachPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coachIDLabel)
                    .addComponent(coachIDValue))
                .addGap(18, 18, 18)
                .addGroup(coachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coachFirstNameLabel)
                    .addComponent(coachLastNameLabel)
                    .addComponent(coachFirstYearLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(coachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coachFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coachLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coachFirstYearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(coachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coachPhoneLabel)
                    .addComponent(coachEmailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(coachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coachPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coachEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        panelContainer.addTab("Coach Info", coachPanel);

        idLabel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        idLabel.setText("Member ID:");

        idValueLabel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        idValueLabel.setText("203838");

        firstNameLabel.setText("First Name:");

        firstNameField.setEnabled(false);

        lastNameLabel.setText("Last Name:");

        lastNameField.setEnabled(false);

        birthDateLabel.setText("Birth Date:");

        birthDateSpinner.setModel(new javax.swing.SpinnerDateModel());
        birthDateSpinner.setEditor(new javax.swing.JSpinner.DateEditor(birthDateSpinner, "dd/MM/yyyy"));
        birthDateSpinner.setEnabled(false);

        genderLabel.setText("Gender:");

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        genderComboBox.setEnabled(false);

        tierLabel.setText("Subscription Tier:");

        tierComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basic", "Premium" }));
        tierComboBox.setEnabled(false);

        expiryDateLabel.setText("Expiry Date:");

        expiryDateSpinner.setModel(new javax.swing.SpinnerDateModel());
        expiryDateSpinner.setEditor(new javax.swing.JSpinner.DateEditor(expiryDateSpinner, "dd/MM/yyyy"));
        expiryDateSpinner.setEnabled(false);

        heightLabel.setText("Height:");

        weightLabel.setText("Weight:");

        phoneLabel.setText("Phone Number:");

        cmLabel.setText("cm");

        kgLabel.setText("kg");

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        errorMessage.setForeground(new java.awt.Color(255, 0, 0));
        errorMessage.setText("jLabel1");

        javax.swing.GroupLayout personalPanelLayout = new javax.swing.GroupLayout(personalPanel);
        personalPanel.setLayout(personalPanelLayout);
        personalPanelLayout.setHorizontalGroup(
            personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tierComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tierLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(birthDateSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(birthDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personalPanelLayout.createSequentialGroup()
                        .addComponent(idLabel)
                        .addGap(18, 18, 18)
                        .addComponent(idValueLabel))
                    .addComponent(firstNameField, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalPanelLayout.createSequentialGroup()
                        .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(genderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(expiryDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(genderComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(expiryDateSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(lastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastNameField))
                        .addGap(18, 18, 18)
                        .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(personalPanelLayout.createSequentialGroup()
                                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(weightField, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(heightField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(kgLabel)
                                    .addComponent(cmLabel)))
                            .addComponent(phoneField)
                            .addComponent(weightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(heightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(errorMessage))
                .addGap(0, 190, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateButton)
                .addContainerGap())
        );
        personalPanelLayout.setVerticalGroup(
            personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idValueLabel)
                    .addComponent(errorMessage))
                .addGap(18, 18, 18)
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(lastNameLabel)
                    .addComponent(heightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmLabel))
                .addGap(18, 18, 18)
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthDateLabel)
                    .addComponent(genderLabel)
                    .addComponent(weightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kgLabel))
                .addGap(18, 18, 18)
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tierLabel)
                    .addComponent(expiryDateLabel)
                    .addComponent(phoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tierComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiryDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(updateButton)
                .addContainerGap())
        );

        panelContainer.addTab("Personal Info", personalPanel);

        getContentPane().add(panelContainer);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void weekSelectorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_weekSelectorItemStateChanged
        // Skip If this is a Unselection Event
        if (evt.getStateChange() == java.awt.event.ItemEvent.DESELECTED) return;
        
        // Get Selected Schedule and Update Table
        Schedule s = (Schedule) weekSelector.getSelectedItem();
        setSchedule(s);
    }//GEN-LAST:event_weekSelectorItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Connect to Database if Not Connected
        if (!DBHandler.isConnected()) DBHandler.init();
        
        // Update Info in All Interfaces
        updateCoachInfo();
        updateClientInfo();
        updateSchedules();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Close Connection to Database
        DBHandler.close();
    }//GEN-LAST:event_formWindowClosing

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // Validate Info in Fields
        if (!validateInfo()) return;
        
        // Get Info
        this.user.setHeight(Float.parseFloat(heightField.getText()));
        this.user.setWeight(Float.parseFloat(weightField.getText()));
        this.user.setPhoneNumber(phoneField.getText());
        
        // Remove Error Messages if There is
        // And Update User Info in Database and Interface
        errorMessage.setVisible(false);
        updateClientInfo();
        ClientDA.updateClient(this.user);
    }//GEN-LAST:event_updateButtonActionPerformed

    private boolean validateInfo() {
        // Sensitive Info
        String phone = phoneField.getText();
        String height = heightField.getText();
        String weight = weightField.getText();
        
        // Validate Each Field
        if (!Validator.isPhone(phone))
            return CommonHelper.sendError(errorMessage, "Invalid Phone Number");
        if (!Validator.isDecimal(height))
            return CommonHelper.sendError(errorMessage, "Invalid Height");
        if (!Validator.isDecimal(weight))
            return CommonHelper.sendError(errorMessage, "Invalid Weight");
        
        // Return True if All Fields are Valid
        return true;
    }
    private void updateClientInfo() {
        // Set Info into Appropriate Fields
        idValueLabel.setText(String.valueOf(this.user.getId()));
        firstNameField.setText(this.user.getFirstName());
        lastNameField.setText(this.user.getLastName());
        birthDateSpinner.setValue(this.user.getBirthDate());
        genderComboBox.setSelectedIndex(
                CommonHelper.parseGender(this.user.getGender())
        );
        tierComboBox.setSelectedIndex(
                CommonHelper.parseTier(this.user.getTier())
        );
        expiryDateSpinner.setValue(this.user.getBirthDate());
        heightField.setText(String.valueOf(this.user.getHeight()));
        weightField.setText(String.valueOf(this.user.getWeight()));
        phoneField.setText(this.user.getPhoneNumber());
    }
    private void updateCoachInfo() {
        // Get Client Coach
        Coach coach = CoachDA.getCoachById(this.user.getCoachId());
        
        // Set Info into Appropriate Fields
        coachIDValue.setText(String.valueOf(coach.getId()));
        coachFirstNameField.setText(coach.getFirstName());
        coachLastNameField.setText(coach.getLastName());
        coachPhoneField.setText(coach.getPhoneNumber());
        coachEmailField.setText(coach.getEmail());
        coachFirstYearSpinner.setValue(coach.getFirstYearDate());
    }
    private void updateSchedules() {
        // Logging
        LogHandler.info("Gathering Info About User's Schedules");
        
        // Get All Schedules of Client and Set ComboBox
        ArrayList<Schedule> schedules = ScheduleDA.getSchedulesByClient(this.user);
        weekSelector.setModel(CommonHelper.createComboBox(schedules));
        
        // Logging
        LogHandler.info("Gathered User's Schedules Successfully");
    }
    private void setSchedule(Schedule s) {
        // Logging
        LogHandler.info("Getting Exercises Available to the Current Schedule");
        
        // Get All Exercises of Schedule and Sort them
        ArrayList<Exercise> exercises = ExerciseDA.getExercisesBySchedule(s);
        exercises.sort(null);
        
        // Setup Table Columns and Model
        DefaultTableModel model = new DefaultTableModel() {
            Class[] types = {
                String.class, Integer.class, Integer.class
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        };
        model.addColumn("Exercise");
        model.addColumn("Reps");
        model.addColumn("Sets");
        
        // Set Each Exercise's Data Into the Table
        for (Exercise e : exercises) {
            Object[] data = new Object[3];
            
            data[0] = e.getName();
            data[1] = e.getReps();
            data[2] = e.getSets();
            
            model.addRow(data);
        }
        
        // Update Tthe Table with the New Data
        trainingSchedule.setModel(model);
        
        // Logging
        LogHandler.info("Exercises are Available to the Current Schedule now");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthDateLabel;
    private javax.swing.JSpinner birthDateSpinner;
    private javax.swing.JLabel cmLabel;
    private javax.swing.JTextField coachEmailField;
    private javax.swing.JLabel coachEmailLabel;
    private javax.swing.JTextField coachFirstNameField;
    private javax.swing.JLabel coachFirstNameLabel;
    private javax.swing.JLabel coachFirstYearLabel;
    private javax.swing.JSpinner coachFirstYearSpinner;
    private javax.swing.JLabel coachIDLabel;
    private javax.swing.JLabel coachIDValue;
    private javax.swing.JTextField coachLastNameField;
    private javax.swing.JLabel coachLastNameLabel;
    private javax.swing.JPanel coachPanel;
    private javax.swing.JTextField coachPhoneField;
    private javax.swing.JLabel coachPhoneLabel;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JLabel expiryDateLabel;
    private javax.swing.JSpinner expiryDateSpinner;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField heightField;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idValueLabel;
    private javax.swing.JLabel kgLabel;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTabbedPane panelContainer;
    private javax.swing.JPanel personalPanel;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JComboBox<String> tierComboBox;
    private javax.swing.JLabel tierLabel;
    private javax.swing.JPanel trainingPanel;
    private javax.swing.JTable trainingSchedule;
    private javax.swing.JScrollPane trainingScheduleContainer;
    private javax.swing.JButton updateButton;
    private javax.swing.JComboBox<String> weekSelector;
    private javax.swing.JLabel weekSelectorLabel;
    private javax.swing.JTextField weightField;
    private javax.swing.JLabel weightLabel;
    // End of variables declaration//GEN-END:variables
    
    private Client user;
}
