/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itse322;

/**
 *
 * @author Zenjar
 */
public class ClientUI extends javax.swing.JFrame {

    /**
     * Creates new form ClientUI
     */
    public ClientUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContainer = new javax.swing.JTabbedPane();
        trainingPanel = new javax.swing.JPanel();
        weekSelectorLabel = new javax.swing.JLabel();
        weekSelector = new javax.swing.JComboBox<>();
        trainingScheduleContainer = new javax.swing.JScrollPane();
        trainingSchedule = new javax.swing.JTable();
        coachPanel = new javax.swing.JPanel();
        coachIDLabel = new javax.swing.JLabel();
        coachIDValue = new javax.swing.JLabel();
        coachFirstNameLabel = new javax.swing.JLabel();
        coachLastNameLabel = new javax.swing.JLabel();
        coachPhoneNumberLabel = new javax.swing.JLabel();
        coachEmailLabel = new javax.swing.JLabel();
        coachFirstNameValue = new javax.swing.JLabel();
        coachLastNameValue = new javax.swing.JLabel();
        coachPhoneNumberValue = new javax.swing.JLabel();
        coachEmailValue = new javax.swing.JLabel();
        coachBioLabel = new javax.swing.JLabel();
        coachBioScrollPane = new javax.swing.JScrollPane();
        coachBioTextArea = new javax.swing.JTextArea();
        personalPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        idValueLabel = new javax.swing.JLabel();
        birthDateLabel = new javax.swing.JLabel();
        birthDateTextField = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        genderTextField = new javax.swing.JTextField();
        subTypeLabel = new javax.swing.JLabel();
        subTypeComboBox = new javax.swing.JComboBox<>();
        expiryDateLabel = new javax.swing.JLabel();
        expiryDateTextField = new javax.swing.JTextField();
        heightLabel = new javax.swing.JLabel();
        heightTextField = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JTextField();
        cmLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        weightTextField = new javax.swing.JTextField();
        kgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        weekSelectorLabel.setText("Choose Day of the Week:");

        weekSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday" }));
        weekSelector.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                weekSelectorItemStateChanged(evt);
            }
        });

        trainingSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Pushups",  new Integer(3),  new Integer(10)},
                {"Pullups",  new Integer(3),  new Integer(12)},
                {"Dips",  new Integer(2),  new Integer(12)},
                {"Body Rows",  new Integer(3),  new Integer(10)},
                {"Squats",  new Integer(3),  new Integer(8)},
                {"Bicep Curls",  new Integer(2),  new Integer(10)}
            },
            new String [] {
                "Exercise", "Sets", "Reps"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        trainingSchedule.setShowHorizontalLines(true);
        trainingSchedule.setShowVerticalLines(true);
        trainingSchedule.getTableHeader().setReorderingAllowed(false);
        trainingScheduleContainer.setViewportView(trainingSchedule);

        javax.swing.GroupLayout trainingPanelLayout = new javax.swing.GroupLayout(trainingPanel);
        trainingPanel.setLayout(trainingPanelLayout);
        trainingPanelLayout.setHorizontalGroup(
            trainingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(weekSelectorLabel)
                .addGap(18, 18, 18)
                .addComponent(weekSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(trainingPanelLayout.createSequentialGroup()
                .addComponent(trainingScheduleContainer)
                .addGap(226, 226, 226))
        );
        trainingPanelLayout.setVerticalGroup(
            trainingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(trainingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weekSelectorLabel)
                    .addComponent(weekSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(trainingScheduleContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(318, Short.MAX_VALUE))
        );

        panelContainer.addTab("Training Schedule", trainingPanel);

        coachIDLabel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        coachIDLabel.setText("Coach ID:");

        coachIDValue.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        coachIDValue.setText("232");

        coachFirstNameLabel.setText("First Name:");

        coachLastNameLabel.setText("Last Name:");

        coachPhoneNumberLabel.setText("Phone Number:");

        coachEmailLabel.setText("E-mail:");

        coachFirstNameValue.setText("Ali");

        coachLastNameValue.setText("Ali");

        coachPhoneNumberValue.setText("0919273723");

        coachEmailValue.setText("username@email.com");

        coachBioLabel.setText("Biography:");

        coachBioTextArea.setEditable(false);
        coachBioTextArea.setColumns(20);
        coachBioTextArea.setRows(5);
        coachBioTextArea.setText("Lorem Ipsum akljsdoijndopk\n");
        coachBioScrollPane.setViewportView(coachBioTextArea);

        javax.swing.GroupLayout coachPanelLayout = new javax.swing.GroupLayout(coachPanel);
        coachPanel.setLayout(coachPanelLayout);
        coachPanelLayout.setHorizontalGroup(
            coachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coachPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(coachEmailLabel)
                    .addComponent(coachPhoneNumberLabel)
                    .addComponent(coachLastNameLabel)
                    .addComponent(coachFirstNameLabel)
                    .addComponent(coachIDLabel))
                .addGap(18, 18, 18)
                .addGroup(coachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coachIDValue)
                    .addComponent(coachEmailValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coachFirstNameValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coachLastNameValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coachPhoneNumberValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(coachBioLabel)
                .addGap(18, 18, 18)
                .addComponent(coachBioScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(447, Short.MAX_VALUE))
        );
        coachPanelLayout.setVerticalGroup(
            coachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coachPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coachIDLabel)
                    .addComponent(coachIDValue))
                .addGap(18, 18, 18)
                .addGroup(coachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(coachPanelLayout.createSequentialGroup()
                        .addGroup(coachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coachFirstNameLabel)
                            .addComponent(coachFirstNameValue)
                            .addComponent(coachBioLabel))
                        .addGap(18, 18, 18)
                        .addGroup(coachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coachLastNameLabel)
                            .addComponent(coachLastNameValue))
                        .addGap(18, 18, 18)
                        .addGroup(coachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coachPhoneNumberLabel)
                            .addComponent(coachPhoneNumberValue)))
                    .addComponent(coachBioScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(coachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coachEmailLabel)
                    .addComponent(coachEmailValue))
                .addContainerGap(343, Short.MAX_VALUE))
        );

        panelContainer.addTab("Coach Info", coachPanel);

        firstNameLabel.setText("First Name:");

        firstNameTextField.setForeground(new java.awt.Color(102, 102, 102));
        firstNameTextField.setText("Ali");
        firstNameTextField.setEnabled(false);
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        lastNameLabel.setText("Last Name:");

        lastNameTextField.setEditable(false);
        lastNameTextField.setForeground(new java.awt.Color(102, 102, 102));
        lastNameTextField.setText("Ali");
        lastNameTextField.setEnabled(false);
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        idLabel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        idLabel.setText("Member ID:");

        idValueLabel.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        idValueLabel.setText("203838");

        birthDateLabel.setText("Brith Date:");

        birthDateTextField.setEditable(false);
        birthDateTextField.setForeground(new java.awt.Color(102, 102, 102));
        birthDateTextField.setText("2000/1/1");
        birthDateTextField.setEnabled(false);

        genderLabel.setText("Gender:");

        genderTextField.setEditable(false);
        genderTextField.setForeground(new java.awt.Color(102, 102, 102));
        genderTextField.setText("male");
        genderTextField.setEnabled(false);

        subTypeLabel.setText("Subscription Type:");

        subTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basic" }));
        subTypeComboBox.setEnabled(false);

        expiryDateLabel.setText("Expiry Date:");

        expiryDateTextField.setText("2000/1/1");
        expiryDateTextField.setEnabled(false);

        heightLabel.setText("Height:");

        heightTextField.setText("185");
        heightTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightTextFieldActionPerformed(evt);
            }
        });

        phoneNumberLabel.setText("Phone Number:");

        phoneNumberTextField.setText("0918273734");

        cmLabel.setText("cm");

        weightLabel.setText("Weight:");

        weightTextField.setText("82");

        kgLabel.setText("kg");

        javax.swing.GroupLayout personalPanelLayout = new javax.swing.GroupLayout(personalPanel);
        personalPanel.setLayout(personalPanelLayout);
        personalPanelLayout.setHorizontalGroup(
            personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idLabel)
                    .addComponent(firstNameLabel)
                    .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lastNameLabel)
                        .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(genderLabel)
                            .addComponent(birthDateLabel))))
                .addGap(18, 18, 18)
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalPanelLayout.createSequentialGroup()
                        .addComponent(idValueLabel)
                        .addContainerGap(989, Short.MAX_VALUE))
                    .addGroup(personalPanelLayout.createSequentialGroup()
                        .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(personalPanelLayout.createSequentialGroup()
                                    .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(phoneNumberLabel))
                                .addComponent(expiryDateLabel)
                                .addGroup(personalPanelLayout.createSequentialGroup()
                                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(subTypeLabel))
                                .addComponent(heightLabel))
                            .addComponent(birthDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personalPanelLayout.createSequentialGroup()
                                .addComponent(subTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(weightLabel)
                                .addGap(18, 18, 18)
                                .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(kgLabel))
                            .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expiryDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(personalPanelLayout.createSequentialGroup()
                                .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmLabel)))
                        .addGap(0, 501, Short.MAX_VALUE))))
        );
        personalPanelLayout.setVerticalGroup(
            personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idValueLabel))
                .addGap(18, 18, 18)
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subTypeLabel)
                    .addComponent(subTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightLabel)
                    .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kgLabel))
                .addGap(18, 18, 18)
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiryDateLabel)
                    .addComponent(expiryDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthDateLabel)
                    .addComponent(birthDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightLabel)
                    .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmLabel))
                .addGap(24, 24, 24)
                .addGroup(personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberLabel)
                    .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(313, Short.MAX_VALUE))
        );

        panelContainer.addTab("Personal Info", personalPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void weekSelectorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_weekSelectorItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.DESELECTED) return;
        
        String weekDay = weekSelector.getSelectedItem().toString();
        System.out.println("Selected: " + weekDay);
    }//GEN-LAST:event_weekSelectorItemStateChanged

    private void heightTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightTextFieldActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthDateLabel;
    private javax.swing.JTextField birthDateTextField;
    private javax.swing.JLabel cmLabel;
    private javax.swing.JLabel coachBioLabel;
    private javax.swing.JScrollPane coachBioScrollPane;
    private javax.swing.JTextArea coachBioTextArea;
    private javax.swing.JLabel coachEmailLabel;
    private javax.swing.JLabel coachEmailValue;
    private javax.swing.JLabel coachFirstNameLabel;
    private javax.swing.JLabel coachFirstNameValue;
    private javax.swing.JLabel coachIDLabel;
    private javax.swing.JLabel coachIDValue;
    private javax.swing.JLabel coachLastNameLabel;
    private javax.swing.JLabel coachLastNameValue;
    private javax.swing.JPanel coachPanel;
    private javax.swing.JLabel coachPhoneNumberLabel;
    private javax.swing.JLabel coachPhoneNumberValue;
    private javax.swing.JLabel expiryDateLabel;
    private javax.swing.JTextField expiryDateTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField genderTextField;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JTextField heightTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idValueLabel;
    private javax.swing.JLabel kgLabel;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTabbedPane panelContainer;
    private javax.swing.JPanel personalPanel;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JComboBox<String> subTypeComboBox;
    private javax.swing.JLabel subTypeLabel;
    private javax.swing.JPanel trainingPanel;
    private javax.swing.JTable trainingSchedule;
    private javax.swing.JScrollPane trainingScheduleContainer;
    private javax.swing.JComboBox<String> weekSelector;
    private javax.swing.JLabel weekSelectorLabel;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JTextField weightTextField;
    // End of variables declaration//GEN-END:variables
}
